data_folder: '/data/isshamie/TSS/NCBI_PICR_103_Processed/'
results: '/data/isshamie/TSS/Analysis/Analysis_03302020/Results/'
figures: '/data/isshamie/TSS/Analysis/Analysis_03302020/Results/'
# RNAseq
RNAseq_QC: '/data/isshamie/TSS/NCBI_PICR_103_Processed/RNAseq/2017_12_15_hamster_Seq/fastqc/'
RNAseq_folder: '/data/isshamie/TSS/NCBI_PICR_103_Processed/RNAseq/2017_12_15_hamster_Seq/'


pipeline_path: '/data/isshamie/TSS/Analysis/src/'
tissues: BMDM1hKLA,BMDMwt,Brain,FemaleReproductive,Heart,Kidney,Liver,Lung,MiscOrgans,Muscle,Pancreas,Spleen,CHO #Skin, Total, Intestine 

ref_fa: '/data/isshamie/genome/hamster/ncbi_anno_103/GCF_003668045.1_CriGri-PICR/GCF_003668045.1_CriGri-PICR_genomic.fna' #'/data/isshamie/genome/picr_final/picr.fa'
annotation: '/data/isshamie/genome/hamster/ncbi_anno_103/GCF_003668045.1_CriGri-PICR/GCF_003668045.1_CriGri-PICR_genomic.gff'  #'/data/isshamie/genome/picr_final/final.gff3'
annotation_gtf: '/data/isshamie/genome/hamster/ncbi_anno_103/GCF_003668045.1_CriGri-PICR/GCF_003668045.1_CriGri-PICR_genomic.gtf'

alt_annotation:  /data/isshamie/genome/hamster/ncbi_anno_103/alt_CriGri-PICR_top_level.gff3
alt_annotation_gtf: '/data/isshamie/genome/ncbi_anno_103/alt_CriGri-PICR_top_level.gtf' #'/data/isshamie/genome/picr_final/final.gtf'

# No longer needed since in subfolder
# mRNA_peak_file: '/data/isshamie/genome/ncbi_anno_103/mRNA_final.peak'
# mRNA_peak_150_file: '/data/isshamie/genome/ncbi_anno_103/mRNA_final_150.peak'
# tss_annotation: '/data/isshamie/genome/ncbi_anno_103/start_site_mRNA_final.tsv' #'/data/isshamie/genome/picr_final/start_site_mRNA_final.tsv'
# cds_annotation: '/data/isshamie/genome/ncbi_anno_103/CDS.bed'

## Suplpemental
motif_folder: '/data/isshamie/TSS/Analysis/supplemental/homer_motifs/'
supplemental: '/data/isshamie/TSS/Analysis/supplemental'

cho_rna_file: '/data/shangzhong/DE/tpm_using_picr.txt'

htseq_anno_source: 'ncbi'  # alternative values: 'ncbi', 'ensembl' or leave it empty.
strand_specific: 'yes'  # 'yes, no, reverse'
id_name: 'id' # if you want gene id in the count result, set 'id', if you want gene name, set 'name'
