## Defaults

## Parameters for the new NCBI PICR annotation (Anno 103), where they
# created the annotation using the PICR genome

outdir: "output/"
results: "/data/isshamie/TSS/Analysis/TSS_code/data/processed/" #NARresubmission"
META_SAMPLES: '/data/isshamie/TSS/Analysis/Analysis_03302020/parameters/samples.tsv'
peaks_dir: '/data/isshamie/TSS/Analysis/Analysis_NCBI_PICR/f04_peaks/'

ncbi_picr: "/data/isshamie/TSS/Analysis/Analysis_03302020/Results/analysis_ncbi_picr"

atac_f : "/data/isshamie/TSS/Analysis/Analysis_NCBI_PICR/Results/ATAC_results/CHO/ATAC_ppr.naive_overlap.narrowPeak.sort"
all_atac : "/data/isshamie/TSS/Analysis/Analysis_NCBI_PICR/Results/ATAC_results/ATAC_merge.bed"

## Global
# Paths
global:
  PREFIX: 'ncbi_picr_103'
  ROOT_DIR: '/data/isshamie/TSS/'
  DATA_DIR: '/data/isshamie/TSS/NCBI_PICR_103_Processed/'
  RESULTS: '/data/isshamie/TSS/Analysis/TSS_code/data/processed/'
  SUPPLEMENTAL_DIR: '/data/isshamie/TSS/Analysis/supplemental/'

  PIPELINE: '/data/isshamie/TSS/Analysis/TSS_code/tss'

  TISSUES:
    - BMDM1hKL
    - BMDMwt
    - Brain
    - FemaleReproductive
    - Heart
    - Kidney
    - Liver
    - Lung
    - MiscOrgans
    - Muscle
    - Pancreas
    - Spleen
    - CHO

    #- Intestine
#    - Skin
#    - Total
  # meta file for names
  META_FILE: '/data/isshamie/TSS/Analysis/Analysis_03302020/parameters/samples.tsv'
  clean: True


MERGE_TISSUES:
  - all
  - bmdm

stages:
#    - reference
    - move_peaks
    - merged
    - gene_centric
    - tissues_collapse
    - sample_peaks_near_tss
    - output_peaks
    - atac
    - histogram



GENOME_FA: '/data/isshamie/genome/ncbi_anno_103/GCF_003668045.1_CriGri-PICR_genomic.fna'
ANNOTATION:
  - '/data/isshamie/genome/hamster/syn20999279_picr.gff'
#  -  "/data/isshamie/genome/hamster/ncbi_anno_103/GCF_003668045.1_CriGri-PICR/GCF_003668045.1_CriGri-PICR_genomic.gff"
#  - "/data/isshamie/genome/hamster/ncbi_anno_103/alt_CriGri-PICR_top_level.gff3"
